# Generated by Django 4.0 on 2023-06-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='images'),
        ),
    ]
