# Generated by Django 4.0 on 2023-06-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_articles_options_articles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, default='default_image.jpg', upload_to='images'),
        ),
    ]
