# Generated by Django 4.2.4 on 2023-08-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artblog',
            name='image',
            field=models.ImageField(blank=True, default='default_image.jpg', upload_to='images/images'),
        ),
    ]
